//! The banking history emitter
//!
//! Turns the household spec into a decade of everyday activity: monthly salary
//! deposits, discretionary spending, a sweep to savings, and a credit-card
//! payment that clears the month's charges. Each year's activity renders to its
//! own `transactions/<year>.ledger`, included from `main.ledger`.
//!
//! Grammar-limited to what the parser accepts today: a date, a cleared status,
//! a payee, and postings with plain amounts.

use std::fmt::Write as _;

use crate::household::{Earner, Household};
use crate::rng::Rng;

/// Merchant names the spending transactions draw a payee from. Unrelated to the
/// category on purpose
const MERCHANTS: [&str; 12] = [
    "Corner Market",
    "Blue Bottle",
    "Transit Authority",
    "City Power",
    "Rent Partners",
    "The Grill",
    "Cinema Eight",
    "Health Clinic",
    "Style Outlet",
    "Fuel Stop",
    "Book Nook",
    "Green Grocer",
];

/// Render one calendar year of activity as ledger text
///
/// The header names the year and repeats the do-not-edit warning. The `rng` is
/// threaded through every month in order, so the stream of draws is a stable
/// function of the seed and the window
pub(crate) fn emit_year(year: i32, household: &Household, rng: &mut Rng) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "; firepath transactions for {year}");
    out.push_str("; generated by `just gen-fixtures`, do not edit by hand\n\n");
    for month in 1..=12u32 {
        emit_month(&mut out, year, month, household, rng);
    }
    out
}

/// Append one month of activity to `out`, in date order
///
/// Transactions are collected with their day, then stable-sorted, so the month
/// reads top to bottom by date while ties keep the order they were emitted in.
/// The sort never reorders the draws themselves, so output order and the rng
/// stream stay independent
fn emit_month(out: &mut String, year: i32, month: u32, household: &Household, rng: &mut Rng) {
    let accounts = &household.accounts;
    let mut entries: Vec<(u32, String)> = Vec::new();

    // Salary lands on the first: checking rises, the earner's income account
    // balances it, one deposit per earner
    for earner in household.earners {
        let pay = monthly_pay(earner, year);
        let deposit = transaction(
            year,
            month,
            1,
            earner.employer,
            Flow {
                debit: accounts.checking,
                cents: pay,
                credit: earner.income_account,
            },
        );
        entries.push((1, deposit));
    }

    // A sweep to savings, also on the first
    let transfer = 20_000i64.saturating_add(i64::from(rng.below(60_000)));
    let sweep = transaction(
        year,
        month,
        1,
        "Monthly Savings",
        Flow {
            debit: accounts.savings,
            cents: transfer,
            credit: accounts.checking,
        },
    );
    entries.push((1, sweep));

    // Discretionary spending scattered across the month, roughly half of it on
    // the card. The card charges accumulate so the statement can be paid in full
    let days = days_in_month(year, month);
    let count = 6u32.saturating_add(rng.below(7));
    let mut card_charges: i64 = 0;
    for _ in 0..count {
        let category = household.pick_category(rng);
        let amount = 500i64.saturating_add(i64::from(rng.below(19_500)));
        let on_card = rng.below(2) == 0;
        let merchant = pick_merchant(rng);
        let day = 1u32.saturating_add(rng.below(days));
        let source = if on_card {
            card_charges = card_charges.saturating_add(amount);
            accounts.credit
        } else {
            accounts.checking
        };
        let spend = transaction(
            year,
            month,
            day,
            merchant,
            Flow {
                debit: category,
                cents: amount,
                credit: source,
            },
        );
        entries.push((day, spend));
    }

    // Clear the card in full on the last day of the month, but only when it
    // carries a balance, so a card-free month emits no zero-dollar payment.
    // Dating the payment last, after every charge including those drawn onto the
    // final days, keeps the card from reading as overpaid before those charges
    // post. The payment is pushed after the spend loop, so the stable sort keeps
    // it behind any charge that shares the last day
    if card_charges > 0 {
        let payment = transaction(
            year,
            month,
            days,
            "Credit Card Payment",
            Flow {
                debit: accounts.credit,
                cents: card_charges,
                credit: accounts.checking,
            },
        );
        entries.push((days, payment));
    }

    entries.sort_by_key(|(day, _)| *day);
    for (_, text) in entries {
        out.push_str(&text);
    }
}

/// One transaction's money movement: `cents` posts to `debit`, and `credit` is
/// left amountless for the balancer to fill
///
/// Grouped into a struct so the two accounts carry names at the call site and
/// cannot be transposed the way three bare `&str` arguments could
#[derive(Clone, Copy)]
struct Flow<'a> {
    /// Account the amount debits
    debit: &'a str,
    /// The amount in whole cents
    cents: i64,
    /// Account the balancer credits, amountless in the output
    credit: &'a str,
}

/// Render a two-posting transaction: the amount sits on the debit posting and
/// the credit posting is left amountless for the balancer to fill
///
/// The debit account is padded so the amounts line up, and the pad always leaves
/// the two-space column split the parser needs even when the name runs past the
/// pad width
fn transaction(year: i32, month: u32, day: u32, payee: &str, flow: Flow) -> String {
    let mut text = String::new();
    let _ = writeln!(text, "{year:04}-{month:02}-{day:02} * {payee}");
    let _ = writeln!(
        text,
        "    {:<38}  {}",
        flow.debit,
        cents_to_dollars(flow.cents)
    );
    let _ = writeln!(text, "    {}", flow.credit);
    text.push('\n');
    text
}

/// The monthly pay for an earner in a year, the effective annual rate split into
/// twelve. Integer division drops the sub-cent remainder, which is fine while no
/// assertion checks the yearly total
fn monthly_pay(earner: &Earner, year: i32) -> i64 {
    effective_annual(earner, year).checked_div(12).unwrap_or(0)
}

/// The annual rate in effect for a year: the last salary step whose effective
/// year has arrived. The steps are ascending by year, so the final match wins.
/// A year before the first step falls back to that first rate
fn effective_annual(earner: &Earner, year: i32) -> i64 {
    let mut annual = earner.salary.first().map_or(0, |step| step.annual);
    for step in earner.salary {
        if step.effective_year <= year {
            annual = step.annual;
        }
    }
    annual
}

/// Format whole cents as a dollar amount, `708333` becoming `$7083.33` and
/// `-708333` becoming `$-7083.33`
///
/// The sign is split off and reattached to the dollar part so the magnitude
/// formats as a clean pair of fields, the cents always the two-digit remainder of
/// the magnitude. `unsigned_abs` is total even at `i64::MIN`
fn cents_to_dollars(cents: i64) -> String {
    let sign = if cents < 0 { "-" } else { "" };
    let magnitude = cents.unsigned_abs();
    let dollars = magnitude.checked_div(100).unwrap_or(0);
    let remainder = magnitude.checked_rem(100).unwrap_or(0);
    format!("${sign}{dollars}.{remainder:02}")
}

/// Draw a merchant name for a spending payee
fn pick_merchant(rng: &mut Rng) -> &'static str {
    let count = u32::try_from(MERCHANTS.len()).unwrap_or(0);
    let index = usize::try_from(rng.below(count)).unwrap_or(0);
    MERCHANTS.get(index).copied().unwrap_or("Merchant")
}

/// Days in a month, so a drawn spending day is always a real calendar date
fn days_in_month(year: i32, month: u32) -> u32 {
    match month {
        2 if is_leap_year(year) => 29,
        2 => 28,
        4 | 6 | 9 | 11 => 30,
        // The seven 31-day months, and the arm the only caller range 1..=12
        // leaves for the long months to fall into
        _ => 31,
    }
}

/// The Gregorian leap-year rule
fn is_leap_year(year: i32) -> bool {
    let divides = |n: i32| year.checked_rem(n) == Some(0);
    divides(4) && (!divides(100) || divides(400))
}

#[cfg(test)]
#[cfg_attr(coverage_nightly, coverage(off))]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

    use super::{cents_to_dollars, days_in_month, emit_month, emit_year, monthly_pay};
    use crate::household::Household;
    use crate::manifest::DEFAULT_SEED;
    use crate::rng::Rng;

    // Sum every `$D.CC` amount in emitted text as cents, so a whole month's
    // activity collapses to one number for testing
    fn sum_cents(text: &str) -> i64 {
        let mut total: i64 = 0;
        for token in text.split('$').skip(1) {
            let amount: String = token
                .chars()
                .take_while(|c| c.is_ascii_digit() || *c == '.')
                .collect();
            let (dollars, cents) = amount.split_once('.').expect("emitted amounts carry cents");
            let whole: i64 = dollars.parse().expect("dollar part is an integer");
            let frac: i64 = cents.parse().expect("cents part is an integer");
            total = total.saturating_add(whole.saturating_mul(100).saturating_add(frac));
        }
        total
    }

    #[test]
    fn cents_render_with_two_decimal_places() {
        assert_eq!(cents_to_dollars(708_333), "$7083.33");
        assert_eq!(cents_to_dollars(500), "$5.00");
        assert_eq!(cents_to_dollars(20_005), "$200.05");
    }

    #[test]
    fn cents_render_a_negative_with_the_sign_on_the_dollars() {
        assert_eq!(cents_to_dollars(-708_333), "$-7083.33");
        assert_eq!(cents_to_dollars(-5), "$-0.05");
        assert_eq!(cents_to_dollars(-500), "$-5.00");
    }

    #[test]
    fn days_in_month_tracks_the_leap_rule() {
        // 2016 and 2000 are leap, 2015 and 1900 are not
        assert_eq!(days_in_month(2016, 2), 29);
        assert_eq!(days_in_month(2000, 2), 29);
        assert_eq!(days_in_month(2015, 2), 28);
        assert_eq!(days_in_month(1900, 2), 28);
        assert_eq!(days_in_month(2015, 4), 30);
        assert_eq!(days_in_month(2015, 12), 31);
    }

    #[test]
    fn monthly_pay_picks_the_effective_salary_step() {
        let household = Household::sample();
        let alex = household.earners.first().expect("Alex is the first earner");
        // Alex earns $85k from 2015 and $104k from 2019, split into twelfths
        assert_eq!(monthly_pay(alex, 2015), 8_500_000 / 12);
        assert_eq!(monthly_pay(alex, 2018), 8_500_000 / 12);
        assert_eq!(monthly_pay(alex, 2019), 10_400_000 / 12);
        assert_eq!(monthly_pay(alex, 2024), 12_600_000 / 12);
        // A year before the first step falls back to that first rate
        assert_eq!(monthly_pay(alex, 2014), 8_500_000 / 12);
    }

    #[test]
    fn salary_deposits_open_every_month() {
        // The first two lines of any month are the two earners' salary payees,
        // both dated the first
        let household = Household::sample();
        let mut rng = Rng::new(DEFAULT_SEED);
        let mut out = String::new();
        emit_month(&mut out, 2015, 3, &household, &mut rng);
        assert!(out.starts_with("2015-03-01 * Meridian Systems\n"));
        assert!(out.contains("2015-03-01 * Bramble & Co\n"));
    }

    /// Every emitted amount in the first month of the window summed as cents,
    /// the statement payment included, locked so any drift in the emitter or the
    /// seed is caught here rather than only in the manifest hash. Measured from a
    /// fresh generator seeded with the committed seed, so the draws match the
    /// first month of a real run
    const JANUARY_2015_TOTAL_CENTS: i64 = 1_531_713;

    #[test]
    fn the_first_month_total_is_pinned() {
        let household = Household::sample();
        let mut rng = Rng::new(DEFAULT_SEED);
        let mut out = String::new();
        emit_month(&mut out, 2015, 1, &household, &mut rng);
        assert_eq!(sum_cents(&out), JANUARY_2015_TOTAL_CENTS);
    }

    #[test]
    fn a_year_carries_a_header_and_twelve_months_of_deposits() {
        let household = Household::sample();
        let mut rng = Rng::new(DEFAULT_SEED);
        let year = emit_year(2015, &household, &mut rng);
        assert!(year.starts_with("; firepath transactions for 2015\n"));
        // One salary deposit per earner per month, so twelve of each payee
        assert_eq!(year.matches("* Meridian Systems\n").count(), 12);
        assert_eq!(year.matches("* Bramble & Co\n").count(), 12);
    }
}
